[workspace]
authors = ["Vipul Sharma"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "gemm"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025102305,<0.26"
